version: '1.0'

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
  app:
    container_name: my_app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: yarn start:dev
    depends_on:
      - db